spring.application.name=SecurityDemo
spring.security.user.name=${SSS_USER}
spring.security.user.password=${SSS_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${BDS_URL}
spring.datasource.username=${BDS_USER}
spring.datasource.password=${BDS_PASSWORD}
